name: TimeBox
options:
  bundleIdPrefix: com.henning
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false

targets:
  TimeBox:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.henning.timebox
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_STRICT_CONCURRENCY: complete
    entitlements:
      path: Resources/TimeBox.entitlements
      properties:
        com.apple.security.app-sandbox: true

  TimeBoxTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TimeBoxTests
    dependencies:
      - target: TimeBox
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.henning.timebox.tests
        GENERATE_INFOPLIST_FILE: YES

  TimeBoxUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - TimeBoxUITests
    dependencies:
      - target: TimeBox
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.henning.timebox.uitests
        GENERATE_INFOPLIST_FILE: YES
